# Generated by Django 4.2.30 on 2026-09-17 09:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ministry', '0004_drop_attendance_rename_event_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='TZS', max_length=6)),
                ('notes', models.TextField(blank=True, help_text='Overall notes about this budget')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='budget', to='ministry.event')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('transport', 'Transport'), ('food', 'Food & Drinks'), ('venue', 'Venue & Facilities'), ('speakers', 'Speakers / Facilitators Allowance'), ('accommodation', 'Accommodation'), ('materials', 'Materials & Printing'), ('media', 'Media, Sound & Equipment'), ('other', 'Other (Extra)')], default='other', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.CharField(blank=True, max_length=255)),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ministry.eventbudget')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
